name: test_maker_native_app
description: A new Flutter project.

publish_to: "none"

version: 7.0.0+192

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  collection: ^1.16.0
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_inappwebview: ^5.7.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.3
  realm: ^0.9.0+rc
  shimmer: ^2.0.0
  sliver_tools: ^0.2.8

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  uses-material-design: true
