name: test_maker_native_app
description: A new Flutter project.

publish_to: "none"

version: 7.0.0+192

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  app_tracking_transparency: ^2.0.3
  auto_route: ^5.0.4
  cloud_firestore: ^4.4.3
  collection: ^1.16.0
  dartx: ^1.1.0
  firebase_analytics: ^10.1.4
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_crashlytics: ^3.0.15
  firebase_dynamic_links: ^5.0.15
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_inappwebview: ^5.7.1
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  fpdart: ^0.4.0
  freezed_annotation: ^2.2.0
  google_mobile_ads: ^2.3.0
  google_sign_in: ^6.0.1
  hooks_riverpod: ^2.1.3
  http: ^0.13.5
  image_picker: ^0.8.6+1
  in_app_review: ^2.0.6
  package_info: ^2.0.2
  path_provider: ^2.0.12
  realm: ^0.9.0+rc
  riverpod_annotation: ^1.2.1
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  sliver_tools: ^0.2.8

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true
